version: "3"
services:
  mosquitto:
    container_name: "mqtt-broker"
    image: "eclipse-mosquitto:latest"
    restart: unless-stopped
    ports:
      - "1883:1883"
  php80:
    container_name: "mqtt-php80"
    build: "docker/php80"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - .:/var/www/html:z
      - ~/.composer:/.composer:z
  php74:
    container_name: "mqtt-php74"
    build: "docker/php74"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - .:/var/www/html:z
      - ~/.composer:/.composer:z
  php71:
    container_name: "mqtt-php71"
    build: "docker/php71"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - .:/var/www/html:z
      - ~/.composer:/.composer:z
